# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
# services:
#   server:
#     build:
#       context: .
#     environment:
#       NODE_ENV: development # Set NODE_ENV to development for dev mode
#     ports:
#       - 3000:3000
#     volumes:
#       - ./.env:/usr/src/app/.env # Mount the .env file into the container
#       - .:/usr/src/app          # Mount the entire project directory for live updates
#     command: npx nodemon --watch .env --exec "npm run dev" # Use nodemon to watch for changes
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production # Set NODE_ENV to production
    ports:
      - 3000:3000
